# Copyright 2020, LibreCores CI contributors
# SPDX-License-Identifier: MIT

name: 'LibreCores CI with FuseSoC'
description: 'FuseSoC action on LibreCores CI'
inputs:
  arguments:
    description: 'Arguments to the main executable'
    required: false
  core:
    description: 'Core identifier'
    required: false
  core-arguments:
    description: 'Arguments passed to the core at run'
    required: false
  command-arguments:
    description: 'Arguments passed to the command'
    required: false
  libraries:
    description: 'FuseSoC libraries to add'
    required: false
  target:
    description: 'Target'
    required: false
  tool:
    description: 'Tool to use'
    required: false
  pre-run-command:
    description: 'Execute command before the run'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cpu'
  color: 'green'
